CREATE DATABASE COLEGIO_ASISTENCIA;
USE COLEGIO_ASISTENCIA;

-- ----------------------------
-- TABLA: GRADO
-- ----------------------------
CREATE TABLE GRADO (
    ID_GRADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_GRADO VARCHAR(50) NOT NULL
);

-- ----------------------------
-- TABLA: CURSO
-- ----------------------------
CREATE TABLE CURSO (
    ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(50) NOT NULL,
    ID_GRADO INT NOT NULL,
    FOREIGN KEY (ID_GRADO) REFERENCES GRADO(ID_GRADO)
);

-- ----------------------------
-- TABLA: DOCENTE
-- ----------------------------
CREATE TABLE DOCENTE (
    ID_DOCENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    TELEFONO VARCHAR(20),
    DOCUMENTO VARCHAR(20) UNIQUE
);

-- ----------------------------
-- TABLA: MATERIA
-- ----------------------------
CREATE TABLE MATERIA (
    ID_MATERIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_MATERIA VARCHAR(100) NOT NULL,
    ID_DOCENTE INT NOT NULL,
    FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE)
);

-- ----------------------------
-- TABLA: ESTUDIANTE
-- ----------------------------
CREATE TABLE ESTUDIANTE (
    ID_ESTUDIANTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DOCUMENTO VARCHAR(20) UNIQUE,
    FECHA_NACIMIENTO DATE,
    ID_CURSO INT NOT NULL,
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

-- ----------------------------
-- TABLA: HORARIO
-- ----------------------------
CREATE TABLE HORARIO (
    ID_HORARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_MATERIA INT NOT NULL,
    ID_CURSO INT NOT NULL,
    DIA_SEMANA ENUM('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES') NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIA),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

-- ----------------------------
-- TABLA: ASISTENCIA
-- ----------------------------
CREATE TABLE ASISTENCIA (
    ID_ASISTENCIA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ESTUDIANTE INT NOT NULL,
    ID_HORARIO INT NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO ENUM('ASISTIÓ','FALTÓ','TARDANZA','JUSTIFICADO') NOT NULL,
    OBSERVACIONES VARCHAR(255),
    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

-- ----------------------------
-- TABLA: USUARIO (OPCIONAL)
-- ----------------------------
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROL ENUM('ADMIN','DOCENTE') NOT NULL,
    ID_DOCENTE INT NULL,
    FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE)
);


INSERT INTO GRADO (NOMBRE_GRADO) VALUES 
('Grado11');

INSERT INTO CURSO (NOMBRE_CURSO,ID_GRADO) VALUES 
('Curso1103',1);

INSERT INTO DOCENTE (NOMBRE,EMAIL,TELEFONO,DOCUMENTO) VALUES 
('Branndon','Branndon@gmail.com',3132563434,1029144872);

INSERT INTO MATERIA (NOMBRE_MATERIA,ID_DOCENTE) VALUES 
('Matematicas',1);

INSERT INTO ESTUDIANTE (NOMBRE,DOCUMENTO,FECHA_NACIMIENTO,ID_CURSO) VALUES 
('Yerik','79457454','2007-07-05',1);

INSERT INTO HORARIO (ID_MATERIA,ID_CURSO,DIA_SEMANA,HORA_INICIO,HORA_FIN) VALUES 
(1,1,'LUNES','10:00:00','15:00:00');

INSERT INTO ASISTENCIA (ID_ESTUDIANTE,ID_HORARIO,FECHA,ESTADO,OBSERVACIONES) VALUES 
(1,1,'2025-12-15','ASISTIÓ','');

INSERT INTO USUARIO (USERNAME,PASSWORD,ROL,ID_DOCENTE) VALUES 
('Admin','$2y$10$rJTN3FHcbBzlJcoF/v7Wru6kTuXBqAxpViGZ85X4VVucregffEe2i','ADMIN',1);

INSERT INTO DOCENTE (NOMBRE,EMAIL,TELEFONO,DOCUMENTO) VALUES 
('for','for@gmail.com',1234567,6456165161);

INSERT INTO USUARIO (USERNAME,PASSWORD,ROL,ID_DOCENTE) VALUES 
('Profe','$2y$10$wRax2.Z4VPtqs9nj/x3lwuMOPOo0nzRSdgRMtZlMGtY/NHQ0jgk0G','DOCENTE',2);

select*from GRADO;
SELECT ID_DOCENTE, NOMBRE FROM DOCENTE;
select*from HORARIO;